site:
    title: "崔朝将的个人博客"
    subtitle: "关于技术"
    limit: 10
    theme: theme
    lang: zh
    url: "https://homeless2010.github.io/code/public"
    comment: username
    logo: "-/images/avatar.png"
    root: "https://homeless2010.github.io/code/public"
    # link: "{category}/{year}/{month}/{day}/{title}.html"

authors:
    me:
        name: "崔朝将"
        intro: "虚度人生几十载，忽觉时光不复返"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
